name: Frontend Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in ~/.npm on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('KnowledgeSharingVue/knowledge-sharing-vue/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install
        working-directory: KnowledgeSharingVue/knowledge-sharing-vue/

      - name: Lint
        run: npm run lint
        working-directory: KnowledgeSharingVue/knowledge-sharing-vue/

      - name: Build
        run: npm run build
        working-directory: KnowledgeSharingVue/knowledge-sharing-vue/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: KnowledgeSharingVue/knowledge-sharing-vue/dist/
